apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30007
  selector:
      app: my-app
      type: front-end    
